### ISSUE TITLE
Error: "panic: invalid character '\n' in string literal" and mention of "/home/travis/" in panic message

### ISSUE THREAD

**Issue by kmcquade** [GESkunkworks/gossamer#9]
/usr/local/bin/gossamer -a arn:aws:iam::0123456789012:role/myrolename -rolesfile /home/ec2-user/gossamer/roles-all.json

```bash
t=2019-12-05T16:18:00+0000 lvl=info msg="gossamer: assume-role via instance role" version=1.2.15.63
panic: EOF

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/GESkunkworks/gossamer/main.go:58 +0x2b01
```

The `/home/travis/` part is odd.

Any chance I could get some help here?

**Comment by kmcquade** [comment]
@rendicott FYI.
I suspect it had something to do with the size of the Roles file? My original one was 4900 lines, and when I trimmed it down to 2000 lines, it started working properly.

Let me know if there's any chance of fixing this - we could really use this ultra assume role functionality for all our accounts.

**Comment by rendicott** [comment]
I suspect the mention of `/home/travis` is because the binary was compiled by TravisCI's docker container and that's the default home folder. I wouldn't worry too much about that.

The invalid character may be a Windows line ending thing or it may be--as you suspected--a file length issue. 

However, I just successfully tested a 5300 line roles file on MacOS with no issues so maybe it's something else. 

Also, in your sample command you gave you were specifying both a `-a` argument for a single role assumption _and_ a roles file. That shouldn't be necessary as you can just put that `-a` arn in the rolesfile along with the others. For example, here's the command I use all the time to assume many roles using starter creds that require MFA:

```
alias gossa="$GOSSAMERPATH -rolesfile $GOSSFOLDER/roles.json -profile g -serialnumber $MFA -o ~/.aws/credentials -force -tokencode"
```

And then I just run `gossa 7197472` whenever I need creds refreshed.

**Comment by rendicott** [comment]
Closing this request for now as I believe you got your issue resolved. Please reopen if necessary.
